general:
  cryptos: [BTC, DOGE, ETH, LTC]
  stocks: [AAL, AAPL, ACB, AMD, AMZN, BA, BABA, BAC, BIDU, BNTX, BP, BYND, CHK, COST,
    CRM, CUK, DAL, DBA, DIA, DIS, DJI, F, FB, FIT, FXE, GE, GILD, GLD, GOOGL, GXC,
    HAL, IGV, INO, INTC, INX, ITA, IVV, IYT, JETS, JNJ, JPM, KCE, KIE, KO, LQD, LYFT,
    MCD, MSFT, MU, NFLX, NKE, NVAX, NVDA, NXGN, PFE, PYPL, QQQ, SHY, SNAP, SPX, SRS,
    T, TIP, TLT, TSLA, TWLO, TWTR, UAL, UBER, UNG, USO, V, VGK, VIX, VNQ, VXX, WMT,
    WORK, XBI, XHB, XLB, XLE, XLF, XLI, XLK, XLP, XLU, XLV, XLY, XOM, XPH, XRT, XSD,
    ZIV, ZM]
news:
  newpaper3k:
    sources: ['https://abcnews.go.com', 'https://cnn.com', 'https://fool.com', 'https://money.cnn.com/data/markets/',
      'https://slate.com', 'https://techcrunch.com', 'https://www.bbc.com/news', 'https://www.benzinga.com',
      'https://www.bloomberg.com/markets', 'https://www.forbes.com/money', 'https://www.foxnews.com',
      'https://www.huffpost.com', 'https://www.kiplinger.com', 'https://www.nbcnews.com',
      'https://www.nytimes.com', 'https://www.politico.com', 'https://www.theguardian.com/us',
      'https://www.thestreet.com', 'https://www.usatoday.com', 'https://www.washingtonpost.com']
  sources: [Barrons, Benzinga, Bloomberg, BusinessInsider, CNBC, CNN, CoinDesk, IBTimes,
    MarketWatch, Newspaper3k, Reuters, SeekingAlpha, TheStreet, Twitter, Verge, WashingtonPost,
    Yahoo]
  twitter:
    users: [DailyFXTeam, EIAgov, IBDinvestors, KeithMcCullough, LizAnnSonders, PeterLBrandt,
      Ralph_Acampora, RedDogT3, ReformedBroker, RyanDetrick, ScottMinerd, TheStalwart,
      VitalikButerin, WSJMarkets, alaidi, bespokeinvest, breakoutstocks, charliebilello,
      coindesk, cullenroche, elerianm, forexcrunch, jimcramer, nytimesbusiness, paulkrugman,
      rayner_teo, realDonaldTrump, stephanie_link, stlouisfed, stocktwits]
prices:
  cryptos: [BTC, DOGE, ETH, LTC]
  stocks: [AAPL, ACB, AMD, AMZN, BA, BABA, BAC, BIDU, BNTX, BYND, COST, DJI, F, FB,
    FIT, GE, GOOGL, INTC, INX, JPM, LYFT, MSFT, MU, NFLX, NKE, NVDA, PFE, PYPL, SNAP,
    SPX, T, TSLA, TWLO, TWTR, UBER, WMT, WORK, ZM]
stats:
  stocks: [AAPL, AMZN, DJI, FB, GE, GOOGL, INX, LYFT, MSFT, NFLX, PFE, UBER]
