general:
  cryptos: [BTC, DOGE, ETH, LTC]
  stocks: [AAL, AAPL, ACB, AMD, AMZN, APHA, ATVI, AUY, BA, BABA, BAC, BIDU, BNTX,
    BP, BRK.B, BYND, CCL, CGC, CHK, COST, CPRX, CRBP, CRM, CRON, CSCO, CUK, DAL, DBA,
    DIA, DIS, DJI, ET, F, FB, FCEL, FIT, FXE, GE, GILD, GLD, GLUU, GM, GOOGL, GPRO,
    GRPN, GXC, HAL, IGV, INO, INTC, INX, ITA, IVV, IYT, JBLU, JETS, JNJ, JNUG, JPM,
    KCE, KIE, KO, KOS, LK, LQD, LUV, LYFT, MCD, MFA, MGM, MRNA, MRO, MSFT, MU, NCLH,
    NFLX, NIO, NKE, NOK, NRZ, NTDOY, NVAX, NVDA, NXGN, NYMT, OPK, OXY, PCG, PENN,
    PFE, PLUG, PTON, PYPL, QQQ, RCL, ROKU, SAVE, SBUX, SHY, SIRI, SNAP, SNE, SPCE,
    SPHD, SPX, SPY, SQ, SRS, T, TCEHY, TIP, TLRY, TLT, TSLA, TWLO, TWTR, UAL, UBER,
    UNG, USO, V, VGK, VIX, VKTX, VNQ, VOO, VSLR, VTI, VXX, WMT, WORK, XBI, XHB, XLB,
    XLE, XLF, XLI, XLK, XLP, XLU, XLV, XLY, XOM, XPH, XRT, XSD, ZIV, ZM, ZNGA]
news:
  newpaper3k:
    sources: ['https://abcnews.go.com', 'https://cnn.com', 'https://fool.com', 'https://money.cnn.com/data/markets/',
      'https://slate.com', 'https://techcrunch.com', 'https://www.bbc.com/news', 'https://www.benzinga.com',
      'https://www.bloomberg.com/markets', 'https://www.forbes.com/money', 'https://www.foxnews.com',
      'https://www.huffpost.com', 'https://www.kiplinger.com', 'https://www.nbcnews.com',
      'https://www.nytimes.com', 'https://www.politico.com', 'https://www.theguardian.com/us',
      'https://www.thestreet.com', 'https://www.usatoday.com', 'https://www.washingtonpost.com']
  sources: [Barrons, Benzinga, Bloomberg, BusinessInsider, CNBC, CNN, CoinDesk, IBTimes,
    MarketWatch, Newspaper3k, Reuters, SeekingAlpha, TheStreet, Twitter, Verge, WashingtonPost,
    Yahoo]
  twitter:
    users: [DailyFXTeam, EIAgov, IBDinvestors, KeithMcCullough, LizAnnSonders, PeterLBrandt,
      Ralph_Acampora, RedDogT3, ReformedBroker, RyanDetrick, ScottMinerd, TheStalwart,
      VitalikButerin, WSJMarkets, alaidi, bespokeinvest, breakoutstocks, charliebilello,
      coindesk, cullenroche, elerianm, forexcrunch, jimcramer, nytimesbusiness, paulkrugman,
      rayner_teo, realDonaldTrump, stephanie_link, stlouisfed, stocktwits]
prices:
  cryptos: [BTC, DOGE, ETH, LTC]
  stocks: [AAPL, ACB, AMD, AMZN, BA, BABA, BAC, BIDU, BNTX, BYND, COST, DJI, F, FB,
    FIT, GE, GOOGL, INTC, INX, JPM, LYFT, MSFT, MU, NFLX, NKE, NVDA, PFE, PYPL, SNAP,
    SPX, T, TSLA, TWLO, TWTR, UBER, WMT, WORK, ZM]
stats:
  stocks: [AAPL, AMZN, DJI, FB, GE, GOOGL, INX, LYFT, MSFT, NFLX, PFE, UBER]
watch:
  news:
    delay: 10
    sources: [accesswire, barrons, businesswire, cnn, federalreserve, fitch, globenewswire,
      marketwatch, moodys, prnewswire, reuters, rtt, seekingalpha, stat, stocktwits,
      thestreet, usbls]
  prs: {delay: 10}
  stats:
    delay: 10
    sources: [earningscast, finviz, zacks]
  tda:
    news: [AAPL, ABBV, ABT, AGEN, AIM, AKRO, ALDX, ALT, AMGN, AMRN, AMZN, APDN, APLT,
      APM, ARCT, ATHX, AYTU, AZN, BCRX, BIOC, BNTX, CANF, CAPR, CARA, CDTX, CNTG,
      COCP, CPRX, CRBP, CTXR, CVM, CYDY, DAL, DFFN, DVAX, ENTA, EXEL, FATE, GERN,
      GILD, GWPH, HTBX, IMAB, IMGN, IMMU, INO, JNJ, KMDA, KNSA, KPTI, LGND, LJPC,
      LUV, MBRX, MESO, MIST, MNK, MRNA, MTNB, NNVC, NOVN, NVAX, ONCS, ONTX, OPK, PFE,
      PSTI, REGN, SELB, SNGX, SNY, SRNE, TAK, TEVA, TSLA, TTNP, URGN, VBIV, VIR, VKTX,
      VNDA, VSTM, VXRT, WORX, ZYNE]
  twitter:
    GILD: [GileadSciences]
    TSLA: [elonmusk]
    _: [ForexLive, LiveSquawk, MarketCurrents, MoodysInvSvc, RANsquawk, fintel_io,
      newsfilterio, quant_data, realDonaldTrump, stock_titan]
