watch:
  guru: {delay: 10800}
  news:
    delay: 10
    sources: [accesswire, alphastocknews, barrons, benzinga, businessinsider, businesswire,
      cnn, federalreserve, financialtimes, fitch, forbes, globenewswire, marketexclusive,
      marketwatch, moodys, pharmiweb, prnewswire, reuters, rtt, seekingalpha, stat,
      stocktwits, streetinsider, thestreet, usbls]
  prs: {delay: 10}
  sec: {delay: 10}
  stats:
    delay: 10
    sources: [biopharmcatalyst, earningscast, finviz, zacks]
  tda: {delay_prices: 10800}
  twitter:
    GILD: [GileadSciences]
    TSLA: [elonmusk]
    _: [ForexLive, LiveSquawk, MarketCurrents, MoodysInvSvc, RANsquawk, Tickeron,
      WatchlistN, fintel_io, newsfilterio, quant_data, realDonaldTrump, stock_titan,
      sunshineavenue8]
